name: main-worklfow

env:
  IMAGE_REPOSITORY: busser/foobar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Run all unit tests
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Check out the pull request's source code
      - name: Check out source code
        uses: actions/checkout@v2

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "^1.14" # The Go version to download and use

      - name: Print Go version
        run: go version

      # Run unit tests
      - name: Run unit tests
        run: go test -v ./...

  # Build and release
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
      -
        name: Check out source code
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: chrismaddalena/test_repo:latest
