name: main-worklfow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out source code
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "^1.14" # The Go version to download and use
      -
        name: Print Go version
        run: go version
      -
        name: Run unit tests
        run: go test -v ./...

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out source code
        uses: actions/checkout@v2
      -
        name: Build the stack
        run: docker-compose -f local.yml up --build -d
